blank_issues_enabled: false
contact_links:
  - name: ğŸ§ Questions
    url: https://github.com/tomsgad/laravel-beem/discussions
    about: The issuer tracker is focused on reporting bugs or problems. Please use the Discussions tabs for questions!
  - name: ğŸ’¡ Proposals
    url: https://github.com/tomsgad/laravel-beem/discussions
    about: If you have a ğŸ”¥ idea. Please use the Discussions tab for this!
  - name: ğŸ“š Documentation improvements
    url: https://github.com/tomsgad/laravel-beem-docs
    about: Our documentation is open-source, you can make a PR with your suggested changes over there.
  - name: Commercial Support
    url: http://laravel-beem-docs.herokuapp.com/docs/support#commercial
    about: If you need urgent help we can offer this on commercial basis. Send us an e-mail to discuss the posibilities and our hourly rate.